backend:
  name: git-gateway
  branch: first_branch
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Name, name: name, widget: string }
          - { label: Location, name: location, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Scripture, name: scripture, widget: text }
          -   label: Priest,
              name: priest,
              widget: "object",
              fields:
                - { label: "Title", name: "title", widget: "string" }
                - { label: "Image", name: "image", widget: "image" }
                - { label: "Name", name: "name", widget: "string" }
                
            
      - file: "src/pages/services/index.md"
        label: "Services Page"
        name: "services"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "services-page",
            }
          - { label: Name, name: name, widget: string }
          - { label: Image, name: image, widget: image }
          - {
              label: Services,
              name: services,
              widget: list,
              fields:
                [
                  { label: Name, name: name, widget: string },
                  { label: Image, name: image, widget: image },
                  { label: Text, name: text, widget: text },
                ],
            }

      - file: "src/pages/youth/index.md"
        label: "Youth Page"
        name: "services"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "youth-page",
            }
          - { label: Name, name: name, widget: string }
          - {
              label: Services,
              name: services,
              widget: list,
              fields:
                [
                  { label: Name, name: name, widget: string },
                  { label: Image, name: image, widget: image },
                  { label: Text, name: text, widget: text },
                ],
              